services:
  postgres:
    container_name: postgreSQL
    image: postgres
    restart: unless-stopped
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - backend

  bot:
    container_name: FeedBot
    image: python:3.12
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - ./app:/rel
    command:
      sh -c "python3 /rel/app.py"
    networks:
      - backend

networks:
  backend:
    driver: bridge
